// Auto-generated by `supabase gen types typescript` (via MCP).
// Do not edit by hand — re-run the generator after migrations.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      accounts: {
        Row: {
          created_at: string
          device_id: string | null
          email: string | null
          handle: string
          id: string
          notes: string | null
          password_encrypted: string | null
          phone: string | null
          proxy_label: string | null
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          device_id?: string | null
          email?: string | null
          handle: string
          id?: string
          notes?: string | null
          password_encrypted?: string | null
          phone?: string | null
          proxy_label?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          device_id?: string | null
          email?: string | null
          handle?: string
          id?: string
          notes?: string | null
          password_encrypted?: string | null
          phone?: string | null
          proxy_label?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "accounts_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "devices"
            referencedColumns: ["id"]
          },
        ]
      }
      devices: {
        Row: {
          alias: string | null
          created_at: string
          id: string
          last_seen: string | null
          notes: string | null
          online: boolean
          updated_at: string
        }
        Insert: {
          alias?: string | null
          created_at?: string
          id: string
          last_seen?: string | null
          notes?: string | null
          online?: boolean
          updated_at?: string
        }
        Update: {
          alias?: string | null
          created_at?: string
          id?: string
          last_seen?: string | null
          notes?: string | null
          online?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      jobs: {
        Row: {
          account_id: string | null
          attempts: number
          created_at: string
          device_id: string | null
          error: string | null
          finished_at: string | null
          id: string
          kind: string
          next_run_at: string | null
          payload: Json
          started_at: string | null
          state: Json
          status: string
          updated_at: string
        }
        Insert: {
          account_id?: string | null
          attempts?: number
          created_at?: string
          device_id?: string | null
          error?: string | null
          finished_at?: string | null
          id?: string
          kind: string
          next_run_at?: string | null
          payload?: Json
          started_at?: string | null
          state?: Json
          status?: string
          updated_at?: string
        }
        Update: {
          account_id?: string | null
          attempts?: number
          created_at?: string
          device_id?: string | null
          error?: string | null
          finished_at?: string | null
          id?: string
          kind?: string
          next_run_at?: string | null
          payload?: Json
          started_at?: string | null
          state?: Json
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "devices"
            referencedColumns: ["id"]
          },
        ]
      }
      media: {
        Row: {
          created_at: string
          duration_seconds: number | null
          file_name: string
          height: number | null
          id: string
          kind: string
          mime_type: string | null
          size_bytes: number | null
          storage_path: string
          uploaded_by: string | null
          width: number | null
        }
        Insert: {
          created_at?: string
          duration_seconds?: number | null
          file_name: string
          height?: number | null
          id?: string
          kind: string
          mime_type?: string | null
          size_bytes?: number | null
          storage_path: string
          uploaded_by?: string | null
          width?: number | null
        }
        Update: {
          created_at?: string
          duration_seconds?: number | null
          file_name?: string
          height?: number | null
          id?: string
          kind?: string
          mime_type?: string | null
          size_bytes?: number | null
          storage_path?: string
          uploaded_by?: string | null
          width?: number | null
        }
        Relationships: []
      }
      post_media: {
        Row: {
          media_id: string
          position: number
          post_id: string
        }
        Insert: {
          media_id: string
          position?: number
          post_id: string
        }
        Update: {
          media_id?: string
          position?: number
          post_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "post_media_media_id_fkey"
            columns: ["media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "post_media_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
        ]
      }
      posts: {
        Row: {
          account_id: string
          caption: string | null
          created_at: string
          id: string
          kind: string
          result_log: Json | null
          scheduled_for: string | null
          status: string
          updated_at: string
        }
        Insert: {
          account_id: string
          caption?: string | null
          created_at?: string
          id?: string
          kind: string
          result_log?: Json | null
          scheduled_for?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          account_id?: string
          caption?: string | null
          created_at?: string
          id?: string
          kind?: string
          result_log?: Json | null
          scheduled_for?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "posts_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      warmup_runs: {
        Row: {
          account_id: string
          config: Json
          created_at: string
          finished_at: string | null
          id: string
          log: Json | null
          started_at: string | null
          status: string
        }
        Insert: {
          account_id: string
          config?: Json
          created_at?: string
          finished_at?: string | null
          id?: string
          log?: Json | null
          started_at?: string | null
          status?: string
        }
        Update: {
          account_id?: string
          config?: Json
          created_at?: string
          finished_at?: string | null
          id?: string
          log?: Json | null
          started_at?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "warmup_runs_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      claim_next_job: {
        Args: { p_lock_seconds?: number }
        Returns: {
          account_id: string | null
          attempts: number
          created_at: string
          device_id: string | null
          error: string | null
          finished_at: string | null
          id: string
          kind: string
          next_run_at: string | null
          payload: Json
          started_at: string | null
          state: Json
          status: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "jobs"
          isOneToOne: true
          isSetofReturn: false
        }
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
